### PR TITLE
cpp sol added

### PR DESCRIPTION
**Pull request by aryanksanghvi**
Added cpp solutions of power of 4 and reverse string

### CODE REVIEW

**Comment by aryanksanghvi** [comment]
did u merge it?

**Review by godkingjay — CHANGES_REQUESTED** [review]
Have you tried running this code in LeetCode? Please add the code you entered and tested in LeetCode. It should have this structure:

- #15 
```cpp
class Solution {
/* ... */
public:
	bool isPowerOfFour(int n) {
        /* ... */
    }
	/* ... */
};
```

- #14 
```cpp
class Solution {
/* ... */
public:
	void reverseString(vector<char>& s) {
        /* ... */
    }
	/* ... */
};
```

**Comment by aryanksanghvi** [comment]
Changed accordingly.

**Review by godkingjay — APPROVED** [review]
Thank you for your contribution.

- [x] 342. Power of Four C++ Solution
- [x] 344. Reverse String C++ Solution

--- 
**Closes:**
- #15 
- #14

**Pull request merged**
