### PR TITLE
solution(cpp,java): 343. Integer Break

### LINKED ISSUE #44: problem: 343. Integer Break
# Problem #343([Integer Break](https://leetcode.com/problems/integer-break/) | Dynamic Programmin, Math)

Medium

Given an integer `n`, break it into the sum of `k` **positive integers**, where `k >= 2`, and maximize the product of those integers.

Return the *maximum product you can get.*

## Example 1:

**Input:** `n = 2`
**Output:** `1`
**Explanation:** `2 = 1 + 1, 1 × 1 = 1.`

## Example 2:

**Input:** `n = 10`
**Output:** `36`
**Explanation:** `10 = 3 + 3 + 4, 3 × 3 × 4 = 36.`

## Constraints:

- $2 <= n <= 58$

### PR DESCRIPTION
**Pull request by aakashdeshamne**
Contains solution for Integer-Break problem in both java and c++ also description for solution

### CODE REVIEW

**Review by godkingjay — CHANGES_REQUESTED** [review]
Thank you for your contributions. However there seems to be a problem with your solutions for:

- **C++ Solution**	
image

- **Java Solution**
image


Both solution fails at the same test case.

**Comment by aakashdeshamne** [comment]
Thank you for catching the errors . I appreciate your feedback. I'll make the necessary corrections promptly.

**Comment by godkingjay** [comment]
Are you still working on this?

**Comment by aakashdeshamne** [comment]
no I dont

**Comment by godkingjay** [comment]
> no I dont

I will close this now. Thank you.

**Pull request closed without merging**
